export type Level = "Técnico" | "Bachillerato" | "Licenciatura" | "Maestría";

export type Program = {
  name: string;
  level: Level;
  area: string;
  slug: string;
  legacySlug?: string;
  duration: string;
  campuses: string[];
  summary: string;
  status?: string;
};

export const contacts = {
  whatsapp: "https://wa.me/50684847884?text=Hola%2C%20quiero%20recibir%20informaci%C3%B3n%20sobre%20USL%20Occidente.",
  alajuelaWhatsapp: "https://bit.ly/WAUSLAlajuela2023",
  sanCarlosWhatsapp: "https://bit.ly/WAUSLSanCarlos2023",
  alajuelaEmail: "info@usl.ac.cr",
  sanCarlosEmail: "plataformasancarlos@usl.ac.cr",
};

export const campuses = [
  {
    name: "Sede Alajuela",
    address: "Primer nivel, ingresando por el lado del Polideportivo Monserrat, City Mall, Alajuela.",
    schedule: "Lunes a viernes de 9:00 a. m. a 6:00 p. m. y sábados de 10:00 a. m. a 2:00 p. m.",
    phone: "2440-4545",
    email: contacts.alajuelaEmail,
    maps: "https://goo.gl/maps/3FJPG2AdWBC3jzr16",
    waze: "https://www.waze.com/es/live-map/directions/cr/provincia-de-alajuela/alajuela/usl-alajuela?to=place.ChIJ44cuNkXjoI8RPWNI3HHPtZs",
  },
  {
    name: "Sede San Carlos",
    address: "Segunda planta del Edificio Coopesancarlos R. L., Ciudad Quesada.",
    schedule: "Lunes a viernes de 9:00 a. m. a 6:00 p. m. y sábados de 8:00 a. m. a 12:00 m. d.",
    phone: "4000-1921",
    email: contacts.sanCarlosEmail,
    maps: "https://goo.gl/maps/JX5BagnmBAv8tGmQA",
    waze: "https://www.waze.com/es/live-map/directions/cr/provincia-de-alajuela/alajuela/usl-alajuela?to=place.ChIJ44cuNkXjoI8RPWNI3HHPtZs",
  },
];

export const programs: Program[] = [
  {
    name: "Marketing y Ventas",
    level: "Técnico",
    area: "Negocios",
    slug: "tecnico-en-marketing-y-ventas",
    duration: "1 año, seis módulos bimestrales",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Mercadeo, ventas, investigación, publicidad, estrategia comercial y emprendimiento.",
  },
  {
    name: "Diseño y Desarrollo Web",
    level: "Técnico",
    area: "Tecnología",
    slug: "tecnico-en-diseno-y-desarrollo-web",
    legacySlug: "tecnico-en-diseno-y-desarollo-web",
    duration: "1 año, 192 horas efectivas",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Fundamentos de programación, diseño web, JavaScript, Angular, bases de datos y administración de sitios.",
  },
  {
    name: "Secretariado Ejecutivo",
    level: "Técnico",
    area: "Administración",
    slug: "tecnico-en-secretariado-ejecutivo",
    duration: "1 año, seis módulos bimestrales",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Administración, comunicación escrita y oral, archivo digital, inglés básico, etiqueta y protocolo.",
  },
  {
    name: "Contabilidad y Finanzas",
    level: "Técnico",
    area: "Finanzas",
    slug: "tecnico-en-contabilidad-y-finanzas",
    duration: "1 año, seis módulos bimestrales",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Contabilidad, matemática financiera, presupuesto, auditoría y gestión de información contable.",
  },
  {
    name: "Gestión del Talento y Recurso Humano",
    level: "Técnico",
    area: "Talento humano",
    slug: "tecnico-en-gestion-del-talento-y-recurso-humano",
    duration: "1 año",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Bases administrativas y herramientas para gestión de talento, procesos internos y desarrollo laboral.",
  },
  {
    name: "Asistente Administrativo",
    level: "Técnico",
    area: "Administración",
    slug: "tecnico-en-asistente-administrativo",
    legacySlug: "tecnico-en-diseno-y-desarollo-web-2",
    duration: "1 año",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Programa detectado en el sitio actual con slug heredado incorrecto; contenido final pendiente de validación.",
    status: "<<PENDIENTE: revisar malla oficial por slug heredado incorrecto>>",
  },
  {
    name: "Contratación Administrativa",
    level: "Técnico",
    area: "Administración pública",
    slug: "tecnico-en-contratacion-administrativa",
    legacySlug: "tecnico-en-diseno-y-desarollo-web-3",
    duration: "1 año",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Programa detectado en la API pública; requiere validación de requisitos y plan actualizado.",
    status: "<<PENDIENTE: validar datos oficiales>>",
  },
  {
    name: "Salud Ocupacional",
    level: "Técnico",
    area: "Salud",
    slug: "tecnico-en-salud-ocupacional",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Programa listado en el sitio actual; faltan detalles públicos completos en la extracción.",
  },
  {
    name: "Gestión de Desastres",
    level: "Técnico",
    area: "Gestión del riesgo",
    slug: "tecnico-en-gestion-de-desastres",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Programa listado en el sitio actual; faltan costos, requisitos y malla confirmada.",
  },
  {
    name: "Control de Calidad",
    level: "Técnico",
    area: "Operaciones",
    slug: "tecnico-en-control-de-calidad",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Programa listado en el sitio actual; pendiente completar información oficial.",
  },
  {
    name: "Comercio Exterior y Aduanas",
    level: "Técnico",
    area: "Comercio",
    slug: "tecnico-en-comercio-exterior-y-aduanas",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Aparece en el catálogo de técnicos; pendiente validar página de detalle.",
  },
  {
    name: "Administración de Negocios con énfasis en Contaduría",
    level: "Bachillerato",
    area: "Negocios",
    slug: "administracion-de-negocios-con-enfasis-en-contaduria",
    duration: "<<PENDIENTE: confirmar duración oficial>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Planificación, organización, control de recursos, contabilidad, estadística, derecho y finanzas.",
  },
  {
    name: "Enfermería",
    level: "Bachillerato",
    area: "Salud",
    slug: "enfermeria",
    duration: "<<PENDIENTE: confirmar duración oficial>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Formación en atención, tratamiento, rehabilitación y acompañamiento de la salud humana.",
  },
  {
    name: "Ciencias de la Educación con énfasis en I y II Ciclos",
    level: "Bachillerato",
    area: "Educación",
    slug: "bachillerato-en-ciencias-de-la-educacion-con-enfasis-en-i-y-ii-ciclos",
    duration: "<<PENDIENTE: confirmar duración oficial>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Formación docente para primaria con acompañamiento del proceso de aprendizaje.",
  },
  {
    name: "Administración de Negocios con énfasis en Recursos Humanos",
    level: "Bachillerato",
    area: "Talento humano",
    slug: "bachillerato-en-administracion-de-negocios-con-enfasis-en-recursos-humanos",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Administración, contratación, capacitación, salarios, legislación laboral y cambio organizacional.",
  },
  {
    name: "Administración de Negocios con énfasis en Mercadeo",
    level: "Bachillerato",
    area: "Negocios",
    slug: "bachillerato-en-administracion-de-negocios-con-enfasis-en-mercadeo",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Mercadeo, mercado, administración y estrategia comercial.",
  },
  {
    name: "Administración de Negocios con énfasis en Gestión Municipal",
    level: "Bachillerato",
    area: "Gestión pública",
    slug: "bachillerato-en-administracion-de-negocios-con-enfasis-en-gestion-municipal",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Administración aplicada a gestión municipal y procesos públicos.",
  },
  {
    name: "Administración de Sistemas de Información en Salud",
    level: "Bachillerato",
    area: "Salud",
    slug: "bachillerato-en-administracion-de-sistemas-de-informacion-en-salud",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Registros, sistemas de información, administración y servicios de salud.",
  },
  {
    name: "Ciencias de la Educación con énfasis en I y II Ciclos",
    level: "Licenciatura",
    area: "Educación",
    slug: "licenciatura-en-ciencias-de-la-educacion-con-enfasis-en-i-y-ii-ciclos",
    duration: "8 meses + modalidad de graduación",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Profundización profesional en educación primaria, investigación y práctica educativa.",
  },
  {
    name: "Registros y Sistemas de Información en Salud",
    level: "Licenciatura",
    area: "Salud",
    slug: "licenciatura-en-registros-y-sistemas-de-informacion-en-salud",
    duration: "8 meses + modalidad de graduación",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Gestión y administración de información en salud.",
  },
  {
    name: "Mercadeo",
    level: "Licenciatura",
    area: "Negocios",
    slug: "licenciatura-en-mercadeo",
    duration: "8 meses + modalidad de graduación",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Estrategia, mercado, comunicación, análisis comercial y gestión de marca.",
  },
  {
    name: "Enfermería",
    level: "Licenciatura",
    area: "Salud",
    slug: "licenciatura-en-enfermeria",
    duration: "8 meses + modalidad de graduación",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Atención y rehabilitación de la salud humana con enfoque integral.",
  },
  {
    name: "Derecho",
    level: "Licenciatura",
    area: "Derecho",
    slug: "licenciatura-en-derecho",
    duration: "<<PENDIENTE: confirmar duración oficial>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Historia del derecho, derecho privado, público, laboral, penal, comercial y constitucional.",
    status: "<<PENDIENTE: el sitio actual mezcla copy de otra carrera; validar antes de publicar>>",
  },
  {
    name: "Ciencias de la Educación con énfasis en Administración Educativa",
    level: "Licenciatura",
    area: "Educación",
    slug: "licenciatura-en-ciencias-de-la-educacion-con-enfasis-en-administracion-educativa",
    duration: "8 meses + modalidad de graduación",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Gestión educativa, investigación, ética profesional y administración en centros educativos.",
  },
  {
    name: "Contaduría Pública",
    level: "Licenciatura",
    area: "Finanzas",
    slug: "licenciatura-en-administracion-de-negocios-con-enfasis-en-contaduria-2",
    duration: "8 meses + modalidad de graduación",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Estados financieros, inventarios, diagnóstico financiero, sistemas administrativos y control.",
  },
  {
    name: "Administración de Recursos Humanos",
    level: "Licenciatura",
    area: "Talento humano",
    slug: "licenciatura-en-recursos-humanos",
    duration: "8 meses + modalidad de graduación",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Gestión de contratación, capacitación, salarios, legislación laboral y evaluación de desempeño.",
  },
  {
    name: "Administración de Negocios con énfasis en Reingeniería Administrativa",
    level: "Maestría",
    area: "Negocios",
    slug: "maestria-en-administracion-de-negocios-con-enfasis-en-reingenieria-administrativa",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Gestión administrativa, liderazgo, mejora de procesos y productividad.",
  },
  {
    name: "Salud Pública",
    level: "Maestría",
    area: "Salud",
    slug: "maestria-en-salud-publica",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Diagnóstico, vigilancia, promoción, planificación, investigación y gestión en salud pública.",
  },
  {
    name: "Administración de Negocios con énfasis en Gerencia",
    level: "Maestría",
    area: "Negocios",
    slug: "maestria-en-administracion-de-negocios-con-enfasis-en-gerencia",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Gerencia, dirección de equipos, estrategia, operaciones y gestión organizacional.",
  },
  {
    name: "Salud Mental y Psiquiatría",
    level: "Maestría",
    area: "Salud",
    slug: "maestria-en-salud-mental-y-psiquiatria",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Formación clínica especializada en salud mental y psiquiatría con enfoque integral.",
  },
  {
    name: "Materno Infantil y Obstetricia",
    level: "Maestría",
    area: "Salud",
    slug: "maestria-en-materno-infantil-y-obstetricia",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Especialización en atención materno infantil y obstétrica.",
  },
  {
    name: "Auditoría de Procesamiento Electrónico de Datos",
    level: "Maestría",
    area: "Tecnología",
    slug: "maestria-en-auditoria-de-procesamiento-electronico-de-datos",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Auditoría, sistemas, datos, control interno y tecnología aplicada.",
  },
  {
    name: "Administración de Servicios de Salud",
    level: "Maestría",
    area: "Salud",
    slug: "maestria-en-administracion-de-servicios-de-salud",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Gestión de instituciones sanitarias, dirección de equipos, liderazgo y administración de servicios.",
  },
  {
    name: "Administración de Negocios con énfasis en Recursos Humanos",
    level: "Maestría",
    area: "Talento humano",
    slug: "maestria-en-administracion-de-negocios-con-enfasis-en-recursos-humanos",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Gestión estratégica del talento, liderazgo y desarrollo organizacional.",
  },
  {
    name: "Administración de Negocios con énfasis en Relaciones Económicas Internacionales",
    level: "Maestría",
    area: "Comercio",
    slug: "maestria-en-administracion-de-negocios-con-enfasis-en-relaciones-economicas-internacionales",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Negocios internacionales, relaciones económicas, mercado y estrategia.",
  },
  {
    name: "Salud Pública con énfasis en Epidemiología",
    level: "Maestría",
    area: "Salud",
    slug: "maestria-en-epidemiologia",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Epidemiología, vigilancia, análisis y seguimiento de situaciones de salud.",
  },
  {
    name: "Administración de Negocios con énfasis en Mercadeo Gerencial",
    level: "Maestría",
    area: "Negocios",
    slug: "maestria-en-administracion-de-negocios-con-enfasis-en-mercadeo",
    duration: "<<PENDIENTE>>",
    campuses: ["Alajuela", "San Carlos"],
    summary: "Mercadeo gerencial, investigación, estrategia comercial y administración.",
  },
];

export const news = [
  "Reglamento oficial de la dinámica: Rifa futbolera USL",
  "Charla gratuita: Insuficiencia Renal Crónica",
  "Promociones Matrícula II Cuatrimestre 2026 San Carlos",
  "Promociones Matrícula II Cuatrimestre 2026 Alajuela",
  "Segunda Promoción Matrícula I Cuatrimestre 2026 San Carlos",
  "Segunda Promoción Matrícula I Cuatrimestre 2026 Alajuela",
  "Días USL 2025",
  "Primera Promoción Matrícula I Cuatrimestre 2026 Alajuela",
  "Primera Promoción Matrícula I Cuatrimestre 2026 San Carlos",
  "Promociones Matrícula III Cuatrimestre 2025 San Carlos",
  "Promociones Matrícula III Cuatrimestre 2025 Sede Alajuela",
  "Curso Virtual Básico para la Presentación de Declaraciones ante el Ministerio de Hacienda",
  "Donald Rojas Fernández, exalumno de la USL, asume como nuevo Ministro de Deportes",
  "Sorteo de Campos Clínicos II Cuatrimestre 2025",
  "Promociones Matrícula II Cuatrimestre 2025 Sede Alajuela",
  "Promociones Matrícula II Cuatrimestre 2025 San Carlos",
  "Explorá Nuestros Nuevos Cursos de Informática",
  "Días USL 2024",
];

export const legacyRedirects = [
  ["/informacion/", "/#nosotros"],
  ["/sede-alajuela/", "/#sedes"],
  ["/sede-san-carlos/", "/#sedes"],
  ["/Financiamiento.html", "/#financiamiento"],
  ["/MaestriaAdministracionServiciosSalud.html", "/#carreras"],
  ["/tecnico-en-diseno-y-desarollo-web/", "/#carreras"],
  ["/tecnico-en-diseno-y-desarollo-web-2/", "/#carreras"],
  ["/tecnico-en-diseno-y-desarollo-web-3/", "/#carreras"],
];
